jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "7b:87:16:a4:5a:39:dc:90:17:bf:b0:6c:be:35:f4:e9"
      - run:
          name: Set Github Info
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "$GH_EMAIL"
            git config user.name "Deployment Bot"
      - checkout
      - run:
          name: Install Lerna
          command: npm install -g lerna
      - run:
          name: Set Credentials
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publishing
          command: lerna publish --conventional-commits -y
