jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Install Lerna
          command: npm install -g lerna
      - run:
          name: Publishing
          command: lerna publish --conventional-commits -y
