jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Publishing
          command: lerna publish --conventional-commits -y
