jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "fe:ca:ad:97:61:f3:a7:5d:47:eb:3e:83:71:69:ca:bf"
      - checkout
      - run:
          name: Set Github Info
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "$GH_EMAIL"
            git config user.name "Deployment Bot"
      - run:
          name: Install Lerna
          command: npm install -g lerna
      - run:
          name: Set Credentials
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publishing
          command: lerna publish --conventional-commits -y
